abstract final class AppRoutes {
  static const splash = '/splash';
  static const welcome = '/welcome';
  static const phone = '/phone';
  static const location = '/location';
  static const nickname = '/nickname';
  static const realName = '/real-name';
  static const birthdayOccupation = '/birthday-occupation';
  static const didSmoke = '/did-smoke';
  static const didDrink = '/did-drink';
  static const identify = '/identify';
  static const haveKids = '/have-kids';
  static const whoToMeet = '/who-to-meet';
  static const interest = '/interest';
  static const height = '/height';
  static const weight = '/weight';
  static const lookingFor = '/looking-for';
  static const addPhoto = '/add-photo';
  static const takeSelfie = '/take-selfie';
  static const poseCamera = '/pose-camera';
  static const complete = '/complete';
  static const turnOnNotification = '/turn-on-notification';
  static const allSet = '/all-set';
  static const bottomNavbar = '/bottom-navbar';
}
